### ISSUE TITLE
be able to fetch metadata

### ISSUE THREAD

**Issue by javisantana** [CartoDB/turbo-cartocss#17]
let's imagine we have a turbo-carto like this:

```
#layer {
marker-width: ramp([col], 10, 20, 5, jenks');
}
```

when we call `turbocartocss``
 it would be nice to have something like

```js
 turbocartocss(turbo_carto, datasource, function(err, cartocss, meta) {
console.log(meta['marker-width']) // [1,3,6,9,12]
})
```

That's pretty simple example, let's do a more complex one
```less
#layer {
marker-width: ramp([col], 10, 20, 5, jenks');
[zoom > 10] {
  [value < 10] {
   marker-width: ramp([col], 10, 20, 10, jenks');
  }
}
}
#layer::foo {
marker-width: ramp([col], 10, 20, 5, jenks');
}
#layer::foo2 {
marker-width: ramp([col], 10, 20, 6, jenks');
}
```

In that case the metadata is not a simple object, it needs to be much more complex. My proposal is to have something like the carto parser:

```js
console.log(meta.layers) // 3
console.log(meta.layers[0].evaluate({ zoom: 10, value: 20})['marker-width']) // [1,3,6,9,12]
console.log(meta.layers[2]].evaluate({ zoom: 10, value: 20})['marker-width']) // [1,3,6,9,10,12], one more value
```

The idea behind this is to use this for the editor, so imagine we have a wizard that creates a bubble map ,we could use the meta to create legends

cc @xavijam @rochoa
